export const emptyBun = {
  _id: "",
  name: "",
  type: "bun",
  proteins: 0,
  fat: 0,
  carbohydrates: 0,
  calories: 0,
  price: 0,
  image: "",
  image_mobile: "",
  image_large: "",
  uniqueId: 0,
  index: 0,
}
export const fakeBun = {
  _id: "123ooo",
  name: "bulo4ka",
  type: "bun",
  proteins: 10,
  fat: 20,
  carbohydrates: 30,
  calories: 40,
  price: 50,
  image: "some_image_url",
  image_mobile: "some_image_mobile_url",
  image_large: "some_large_image_url",
  uniqueId: 123.01,
  index: 1,
}
export const anotherFakeBun = {
  _id: "123ooo321",
  name: "bulo4ka227",
  type: "bun",
  proteins: 11,
  fat: 22,
  carbohydrates: 33,
  calories: 44,
  price: 55,
  image: "another_image_url",
  image_mobile: "another_image_mobile_url",
  image_large: "another_large_image_url",
  uniqueId: 123.0123,
  index: 2,
}
export const fakeOrder = {
  createdAt: "2022-02-09T15:56:00.422Z",
  ingredients: [{
      calories: 420,
      carbohydrates: 53,
      fat: 24,
      image: "https://code.s3.yandex.net/react/code/bun-02.png",
      image_large: "https://code.s3.yandex.net/react/code/bun-02-large.png",
      image_mobile: "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      name: "Краторная булка N-200i",
      price: 1255,
      proteins: 80,
      type: "bun",
      _id: "60d3b41abdacab0026a733c6",
  }],
  name: "Space краторный бургер",
  number: 9829,
  status: "done",
  updatedAt: "2022-02-09T15:56:00.735Z",
  _id: "6203e4106d7cd8001b2d4f20"
}
